
services:
  db:
    image: postgres:latest
    container_name: postgres_db_stock
    environment:
      POSTGRES_DB: stock_monitor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
