
services:
  db:
    image: postgres:16
    container_name: postgres_db_stock
    environment:
      POSTGRES_DB: stock_monitor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d stock_monitor"]
      interval: 5s
      timeout: 5s
      retries: 5


  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: >
      bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
      - ./alembic:/app/alembic
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  mcp-server:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    container_name: mcp_server
    environment:
      API_BASE_URL: http://fastapi:8000
    ports:
      - "8100:8100"
    depends_on:
      fastapi:
        condition: service_started
    networks:
      - my_network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    env_file:
      - .env
    volumes:
      - ./streamlit_app:/app/streamlit_app/
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy      
      fastapi:
        condition: service_started
    networks:
      - my_network


volumes:
  postgres_data:

networks:
  my_network:

