
services:
  db:
    image: postgres:latest
    container_name: postgres_db_stock
    environment:
      POSTGRES_DB: stock_monitor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: >
      bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
      - ./alembic:/app/alembic
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
