"""Initial migration

Revision ID: 003155475dd4
Revises: c22cb6ee5238
Create Date: 2024-10-07 18:37:51.217191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003155475dd4'
down_revision = 'c22cb6ee5238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index('ix_watchlists_id')

    op.drop_table('watchlists')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('ix_companies_id')
        batch_op.drop_index('ix_companies_name')
        batch_op.drop_index('ix_companies_ticker_symbol')

    op.drop_table('companies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_id')
        batch_op.drop_index('ix_users_username')

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_username', ['username'], unique=False)
        batch_op.create_index('ix_users_id', ['id'], unique=False)
        batch_op.create_index('ix_users_email', ['email'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ticker_symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='companies_pkey')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('ix_companies_ticker_symbol', ['ticker_symbol'], unique=False)
        batch_op.create_index('ix_companies_name', ['name'], unique=False)
        batch_op.create_index('ix_companies_id', ['id'], unique=False)

    op.create_table('watchlists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rsi_threshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='watchlists_pkey')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index('ix_watchlists_id', ['id'], unique=False)

    # ### end Alembic commands ###
