"""add pegy ratio

Revision ID: 57981a849a68
Revises: f1624e5b4f6e
Create Date: 2026-02-28 16:54:00.248213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57981a849a68'
down_revision = 'f1624e5b4f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triggered', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('_user_ticker_rsi_trigger_uc'), type_='unique')
        batch_op.create_unique_constraint('_user_ticker_rsi_trigger_uc', ['user_id', 'ticker_symbol', 'rsi_threshold', 'triggered'])
        batch_op.drop_column('triggered_rsi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triggered_rsi', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('_user_ticker_rsi_trigger_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_user_ticker_rsi_trigger_uc'), ['user_id', 'ticker_symbol', 'rsi_threshold', 'triggered_rsi'])
        batch_op.drop_column('triggered')

    # ### end Alembic commands ###
