"""add pegy ratio

Revision ID: f1624e5b4f6e
Revises: 
Create Date: 2026-02-28 16:48:55.744662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1624e5b4f6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pegy_ratio', sa.Numeric(), nullable=True))
        batch_op.create_index(batch_op.f('ix_price_history_id'), ['id'], unique=False)

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triggered_rsi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pegy_ratio', sa.Numeric(), nullable=True))
        batch_op.drop_constraint(batch_op.f('_user_ticker_rsi_trigger_uc'), type_='unique')
        batch_op.create_unique_constraint('_user_ticker_rsi_trigger_uc', ['user_id', 'ticker_symbol', 'rsi_threshold', 'triggered_rsi'])
        batch_op.create_index(batch_op.f('ix_watchlist_id'), ['id'], unique=False)
        batch_op.drop_column('triggered')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triggered', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_watchlist_id'))
        batch_op.drop_constraint('_user_ticker_rsi_trigger_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_user_ticker_rsi_trigger_uc'), ['user_id', 'ticker_symbol', 'rsi_threshold', 'triggered'])
        batch_op.drop_column('pegy_ratio')
        batch_op.drop_column('triggered_rsi')

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_id'))
        batch_op.drop_column('pegy_ratio')

    # ### end Alembic commands ###
